spring.application.name=lol-backend
server.servlet.context-path=/api
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/loldb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:loluser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:lolpass}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
